- name: configure frontend server
  hosts: db
  become: yes

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Ensure Nginx is stopped before config
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: Remove default site config
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Remove default html
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download frontend build
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy expense nginx config
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/conf.d/expense.conf
        owner: root
        group: root
        mode: '0644'

    - name: Test nginx config
      ansible.builtin.command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      changed_when: false

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
